### ISSUE TITLE
iohook doesn't ask for input monitoring permission in Mac OS Catalina.

### ISSUE THREAD

**Issue by shafayet2368** [wilix-team/iohook#232] opened 2020-04-01 06:55 UTC
In Mac OS Catalina the have introduced a new permission for keyboard and mouse events tracking that is "Input monitoring". While initializing an app with "iohook" it asks for the Accessibility permission but doesn't ask for the "Input Monitoring" permission. Can anyone help me to fix this issue?

## Expected Behavior
While initializing an app it should ask for "Input monitoring" permission.

## Current Behavior
It does not ask for the "Input Monitoring" permission from mac.

## Your Environment
* Version used: 0.6.5
* Environment name and version: Electron and node.js
* Operating System and version (desktop or mobile): Mac OS Catalina 10.15.4

**Comment by pgupt** [comment] 2020-04-04 04:13
I am also using iohook over Mac Catalina. and our app behaviour is the same. It does not asks for input monitoring. I suppose its normal. What kind of issue are you facing?

**Comment by inomdzhon** [comment] 2020-04-25 13:19
@pgupt iohook should ask access for the "Input Monitoring" permission, but shouldn't for the "Accessibility" permission.
Because the "Input Monitoring" transfer inputs events.

**Comment by ash0x0** [comment] 2021-06-11 20:23
Can't repro. I don't see what the issue is because it does capture correctly. Closing.

**Closed by ash0x0** 2021-06-11 20:23 UTC
