### ISSUE TITLE
The message "would like to control this computer using accessibility features"

### ISSUE THREAD

**Issue by trae-op** [wilix-team/iohook#192] opened 2019-08-15 14:16 UTC
After each app start display the message "**would like to control this computer using accessibility features**". Even if you just add `const ioHook = require('iohook');` the message will display. 
I use **electron v6.0.1**
I have **high sierra 10.13.3**

![image](https://user-images.githubusercontent.com/12648541/63100746-61db6c80-bf80-11e9-90e6-f3dc91d7d9f4.png)

**Comment by Djiit** [comment] 2019-08-16 14:35
Hello,

This is an intended behavior on macOS. Maybe we should state it more clearly in the README ?

**Comment by jbagaresgaray** [comment] 2019-09-02 13:56
Possible duplicate issue on https://github.com/wilix-team/iohook/issues/107

**Comment by Djiit** [comment] 2020-01-20 09:32
Duplicate of #107

**Closed by Djiit** 2020-01-20 09:32 UTC
