### ISSUE TITLE
A build of my app does not work with iohook on windows. Can't find iohook.node

### ISSUE THREAD

**Issue by Maidomax** [wilix-team/iohook#153] opened 2019-03-13 09:37 UTC
I am very new to electron, but I think this error is not on me.
I have an electron app that works well on Ubuntu Linux 18.04, but fails when trying to run it on Windows 10 (64 bit).

## Expected Behavior
I would expect the app to run and work just like on Linux

## Current Behavior
When trying to start the app with `electron .`, the app crashes instantly with a Windows popup error window, and this in the console:
```
C:\Users\maido\Desktop\temp\webueno-tracker>electron .

 App threw an error during load
Error: The specified procedure could not be found.
\\?\C:\Users\maido\Desktop\temp\webueno-tracker\node_modules\iohook\builds\electron-v69-win32-x64\build\Release\iohook.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\maido\Desktop\temp\webueno-tracker\node_modules\iohook\index.js:10:21)
    at Object.<anonymous> (C:\Users\maido\Desktop\temp\webueno-tracker\node_modules\iohook\index.js:397:3)
```

I can in fact find the file that is supposedly missing at the path specified, but the path in the error message seems to be malformed. A similar error appears in the version of the app packaged with `electron-packager` regardless of whether I package it on Windows or Linux

## Possible Solution
Native node extensions are way out of my comfort zone at the moment, but Googling around has brought me to this issue on a different package.
https://github.com/agracio/electron-edge-js/issues/32

As you can see in the issue, the path is malformed in the same way, and it seems to be related to this issue:
https://electronjs.org/docs/tutorial/using-native-node-modules#troubleshooting
Regarding the `win_delay_load_hook`. Which is in the iohook package itself.

## Steps to Reproduce (for bugs)
1. Create an app with electron `4.0.4.`
2. Try and run it on Windows

## Context
The app is supposed to track user activity and put it self on pause if there was no user activity in the last 5 minutes. That is what I am using iohook for. The feature works on Ubuntu Linux 18.04 LTS, but not on Windows. Windows and MacOS users are very important to me. I still have not tested it on a Mac.

## Your Environment
Windows 10 64 bit
Iohook 0.4.0
Electron 4.0.4

**Comment by jakemingolla** [comment] 2019-03-17 22:12
Same thing happens to me when running the https://github.com/wilix-team/iohook/tree/master/examples/electron-example example project

**Comment by GimpMaster** [comment] 2019-03-19 05:14
I'm seeing the same problem with latest ABI version of electron 69.

**Comment by GimpMaster** [comment] 2019-03-19 05:20
Here is the console error I'm getting as well.

Uncaught Error: The specified procedure could not be found.
\\?\H:\test_app\node_modules\iohook\builds\electron-v69-win32-x64\build\Release\iohook.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)
    at Function.Module._load (internal/modules/cjs/loader.js:533)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at Object.<anonymous> (H:\test_app\node_modules\iohook\index.js:10)

console.log('info: ', process.versions.modules);
Yields ABI: 69,
Using "win32", 64 bit
Node version: 10.15.1

**Comment by erfanium** [comment] 2019-03-19 08:50
I have the same Problem on windows 10 x64 , electron 4.1.0 , iohook 0.4.0  on requiring iohook.
err: 
`Error: Cannot find module '.\node_modules\iohook\builds\electron-v69-win32-x64\build\Release\iohook.node'
at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
at Function.Module._resolveFilename (.\electron\dist\resources\electron.asar\common\reset-search-paths.js:43:12)
at Function.Module._load (internal/modules/cjs/loader.js:510:25)
at Module.require (internal/modules/cjs/loader.js:640:17)
at require (internal/modules/cjs/helpers.js:20:18)
at Object. (C.\node_modules\iohook\index.js:10:21)
at Object. (.\node_modules\iohook\index.js:397:3)
at Module._compile (internal/modules/cjs/loader.js:693:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
at Module.load (internal/modules/cjs/loader.js:602:32)`

but it works with node js fine.


What your solution for this?
Does it exist a module for electron (worked on windows) for mouse event like iohook?

**Comment by GimpMaster** [comment] 2019-03-21 03:43
Any updates with this version of iohook and latest version of electron 64-bit windows? if not I'll probably have to downgrade to an older version.

**Comment by anoadragon453** [comment] 2019-03-21 12:13
https://github.com/nodejs/node-addon-api/issues/269#issuecomment-455580129 Seems to be what we have to do. Step 1 is easy enough, though Step 2 will require some code changes (hopefully quite simplistic)

**Comment by GimpMaster** [comment] 2019-03-21 14:31
I'm just curious if anyone has gotten iohook with Electron 4.1.0 ABI 69 working. I just went back to Electron 2.0.0+ for the time being.

**Comment by anoadragon453** [comment] 2019-03-21 14:33
Yep, MacOS and Linux work fine. https://github.com/wilix-team/iohook/issues/144

**Comment by GimpMaster** [comment] 2019-03-27 15:21
Can someone else publish a binary for Windows 10 64-bit? Seems the last release didn't compile properly.

**Comment by Djiit** [comment] 2019-03-27 16:15
@GimpMaster could you help us with this ? https://github.com/wilix-team/iohook/pull/157

**Comment by GimpMaster** [comment] 2019-03-28 04:02
@Djiit Absolutely. Just an FYI...I saw you pushed a new release 0.4.1. I did the following:

npm install https://github.com/wilix-team/iohook.git  -save

This installed 0.4.1. I even confirmed the build folder:

electron-v69-win32-x64\build\Release had the same binaries as what is in the tagged release.

But I still get the following error.

`Uncaught Error: The specified procedure could not be found.
\\?\H:\Fast_Dev\line_app\node_modules\iohook\builds\electron-v69-win32-x64\build\Release\iohook.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)
    at Function.Module._load (internal/modules/cjs/loader.js:533)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at Object.<anonymous> (H:\Fast_Dev\line_app\node_modules\iohook\index.js:10)
    at Object.<anonymous> (H:\Fast_Dev\line_app\node_modules\iohook\index.js:397)`

I'll see what I can do in issue #157

**Comment by Djiit** [comment] 2019-04-26 12:41
I'm closing this since it was resolved elsewere.

**Closed by Djiit** 2019-04-26 12:41 UTC

**Comment by karacas** [comment] 2019-07-20 23:50
@Maidomax 
Maybe this help:
https://github.com/wilix-team/iohook/issues/160

**Comment by Maidomax** [comment] 2019-10-29 13:16
> @Maidomax
> Maybe this help:
> #160

@karacas Did not help :(
Works on some machines, on some not.
