### ISSUE TITLE
Freezes when more than one app use iohook

### ISSUE THREAD

**Issue by JasminDreasond** [wilix-team/iohook#93] opened 2018-07-03 20:02 UTC
## Current Behavior

whenever I open more than one electron application using iohook, it makes the whole operating system freeze for a few seconds.

## Steps to Reproduce (for bugs)
1. Open a Electron application with the the ioHook module.
2. Open a second Electron application with the ioHook module.
3. The second Electron application will freeze when the app start loading.

## Context

I want to use the module in more than one project, but I do not want this type of problem to happen.

## Your Environment

* Version used: 0.2.0
* Nodejs 8.9.3
* Electron 2.0.2
* Windows 10

**Comment by serafimpinto** [comment] 2018-07-09 16:25
Same here! 😞

**Comment by jlsilva1994** [comment] 2018-07-12 11:18
Same here too!
A temporary fix for the Electron apps, if you DON'T want to open a second one, you can use this code only have one app opened, and when you try to open a second one, it redirects you to first one you have open:

`const shouldQuit = app.makeSingleInstance(() => {
  // do your code to redirect to the window here!
})
if (shouldQuit) {
  app.exit() // could use app.quit(), but exit is more fast and prevent other errors
}`

**Comment by JasminDreasond** [comment] 2018-07-15 06:01
sorry, but my problem is not two electron applications repeated. My problem is two different electron applications

**Comment by Djiit** [comment] 2018-07-16 09:53
What you could do is, e.g. write a file somewhere in the user folder and check if it is present before launching the app.

**Comment by JasminDreasond** [comment] 2018-09-08 00:51
@Djiit 
I am confused. Can you explain better please? :c 
the simple fact of the ` var ioHook = require('iohook');` exists, makes everything freeze

**Comment by MiguelSmith** [comment] 2018-09-10 14:07
I am getting the same problem with two nodejs applications, where if the first one has an ioHook module loaded, the second one that opens with an ioHook module loaded lags a lot and causes the cursor and other IO inputs to lag out until the second application is closed.

**Comment by Djiit** [comment] 2018-10-29 13:20
I got it now. Maybe we could tell iohook to only listen once system-wide, and provide a way for users to know it (like triggering an event "IOHookAlreadyListening". Any C++ programmer here ?

**Comment by rscord** [comment] 2019-02-13 20:24
When launching two or more processes with iohook module, my mouse moves like in slow-mo. This is actually a big problem. Imagine if user launches two or more completely different apps that uses iohook module.

```
const {exec} = require('child_process');
const iohook = require('iohook');

iohook.start();

if (process.argv.length === 2) {
	console.log('Launched main');
	iohook.on('keydown', (e) => {
		console.log('Main', e.rawcode);
	});
	exec([`"${process.argv[0]}"`, process.argv[1], '-t'].join(' ')).stdout.pipe(process.stdout);
} else {
	console.log('Launched child');
	iohook.on('keydown', (e) => {
		console.log('Child', e.rawcode);
	});
}
```

**Comment by Lennon925** [comment] 2019-05-17 02:27
@Djiit , this issue hasn't been resolved by now? I have to give up iohook because of this issue.

**Comment by Suhail** [comment] 2019-07-09 21:03
This issue: https://github.com/wilix-team/iohook/issues/176 seems related to this one.

**Comment by Wizek** [comment] 2019-09-02 05:49
This freezing issue is still present. @Djiit, why did you close #145? Did that not solve this problem? Or was something else wrong with that PR?

**Comment by Wizek** [comment] 2019-09-03 19:28
@Lennon925 Did you find an alternative for iohook?

**Comment by Lennon925** [comment] 2019-09-05 08:41
> @Lennon925 Did you find an alternative for iohook?

Acturally not yet. But I am using "robotjs" which can monitor mouse-move event only.

**Comment by Wizek** [comment] 2020-05-09 13:09
As this is still not fixed, I'm switching over to something that seems to work much better: 

https://www.npmjs.com/package/gkm

**Comment by EmptyCrown** [comment] 2020-05-22 20:08
Hey, we just ran into this exact issue (wasn't aware that it was caused by iohook but luckily ran into this thread).

Is there any way to simply detect if there's another instance of iohook and shut down iohook functionality in our app?

**Comment by Wizek** [comment] 2020-05-23 19:33
I'm not aware of that, but I strongly advise against using iohook in any way before this issue is fixed somewhere. Gkm it turns out has quite some issues too. Next I'll look into if I can use Electron.js to be able to respond to global keys.

**Comment by EmptyCrown** [comment] 2020-05-25 00:18
Got it, yeah we've come to the same conclusion but unfortunately, we haven't found a good alternative. We've experimented with the `globalShortcut` that comes with Electron.js, but we'd rather have it listen to a key-binding rather than actually register a shortcut, which can conflict with other shortcuts on the machine. For example, the user is playing a game or something, the shortcuts will be blocked.

**Comment by Wizek** [comment] 2020-05-25 12:00
Is that so? That's strange. I've still yet to experiment with the Electron approach, would be a shame if they couldn't react to a shortcut key that another app is also listening to. Have you perhaps a small reproducible experimental example that I could also try to replicate this? Because if so, their project might be much more active, receptive and interested in fixing this shortcoming of theirs, and we could share it with them too while raising an issue with them.

**Comment by JoeBernardi** [comment] 2020-05-27 18:05
It looks like libuiohook has fixed this issue upstream somewhat recently: https://github.com/kwhat/libuiohook/pull/72

I've yet to try dropping this newer libuiohook version in, but it certainly feels promising.

**Comment by chipimix** [comment] 2020-07-13 10:33
Hello! I'm also experiencing this abnormal behavior! :(
Its really easy to replicate, just run two electron apps which use electron [eg [Loom ](https://www.loom.com/my-videos)or [Cortex](https://crtx.gg/)]  and everything freezes.
Is there any fix on this incoming soon due to the recent libuiohook changes?
Thanks!

**Comment by chevonc** [comment] 2021-02-10 20:30
Put out a PR for a fix for this. Welcoming reviews here: https://github.com/wilix-team/iohook/pull/294

**Comment by michelvermeulen** [comment] 2021-04-02 14:30
Following. I have the same issue

**Closed** 2021-04-06 06:37 UTC
Labels: bug, help wanted
