### ISSUE TITLE
Mouse is auto(Lost mouse controll) move after iohook installation

### ISSUE THREAD

**Issue by tijo123** [wilix-team/iohook#190] opened 2019-08-07 03:41 UTC
Mouse is auto(Lost mouse controll) move after iohook installation

## Expected Behavior
Normal mouse behaviour

## Current Behavior
Some times Mouse is auto(Lost mouse controll) move to top to bottom only after iohook installation

**Comment by Djiit** [comment] 2019-08-07 07:18
Hi there ! We're happy to help. Could you provide us with a minimal reproductible example ? Thanks !

**Comment by tijo123** [comment] 2019-08-07 08:29
Hi all

I have included the working code

var mouse_clicking =0;
var keyboard_clicking =0;

   ioHook.on('keydown', event => {
//console.log(event);
* keyboard_clicking++;*
});

ioHook.on('mouseclick', event => {
  //console.log(event);
//mouse_clicking = event.clicks;
* mouse_clicking++;*
});


ioHook.start();

ioHook.start(true);

*keyboard_clicking* , *mouse_clicking *These two are count of events in
certain intevals

The issue is if i start the process some time the mouse control is
lost(Move different directions without controll)....

I have using node V10 and latest version of electron


Thanks

**Comment by tijo123** [comment] 2019-08-08 06:17
Please check the error while running

**Comment by tijo123** [comment] 2019-08-08 11:26
![Capture](https://user-images.githubusercontent.com/53806091/62699380-05ff6980-b9fd-11e9-917b-646a6bcdb1ee.PNG)

Initial page loading(const ioHook = require('iohook')) show this error on console with lost my mouse clicks 

Electron version -= v6.0.0
Node Version =  v10.14.2
OS = Windows 7

**Comment by Djiit** [comment] 2019-08-08 12:20
Hi there,

In your last comment, I see you are calling `iohook.start()` twice. Is there any particular reason ? You should call it only once.

I don't see any error in your screenshots, juste normal logs. Maybe you uploaded the wrong image ?

Please don't mention everyone. it does not make us want to help you.

**Comment by tijo123** [comment] 2019-08-09 04:52
If i include your library (const ioHook = require('iohook');) Lost my mouse
controls 5 to 10 seconds..
If i remove the library or close the application back the mouse controll.

I have includes  iohook.start() only ones...

Please guide me to find the issue.

**Comment by tijo123** [comment] 2019-08-12 03:36
Hi,

I have packed my electron code. Some systems appliction is not working due
to below error... Can you check..


Uncaught Error: The specified module could not be found.
\\?\C:\Users\ZODIAC
001\AppData\Local\Programs\Hrtrace\resources\app.asar.unpacked\node_modules\iohook\builds\electron-v73-win32-x64\build\Release\iohook.node
    at process.func (electron/js2c/asar.js:155)
    at process.func [as dlopen] (electron/js2c/asar.js:155)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828)
    at Object.func (electron/js2c/asar.js:155)
    at Object.func [as .node] (electron/js2c/asar.js:164)
    at Module.load (internal/modules/cjs/loader.js:645)
    at Function.Module._load (internal/modules/cjs/loader.js:560)
    at Module.require (internal/modules/cjs/loader.js:685)
    at require (internal/modules/cjs/helpers.js:16)
    at Object.<anonymous> (C:\Users\ZODIAC
001\AppData\Local\Programs\Hrtrace\resources\app.asar\node_modules\iohook\index.js:10)
index.html:340 Uncaught ReferenceError: Cannot access 'ioHook' before
initialization

**Comment by Djiit** [comment] 2020-01-20 09:36
Closing this one because of lack of information. Feel free to ping me here if you want to reopen it with more details.

**Closed by Djiit** 2020-01-20 09:36 UTC
Labels: waiting for feedback
