### ISSUE TITLE
Global Key Listeners don't work in builded Electron app on macos

### ISSUE THREAD

**Issue by kolnogorov** [wilix-team/iohook#149] opened 2019-02-28 14:17 UTC
I use ioHook to listen global key events (keydown/keyup). It works when i run app in dev mode, but when i build an app, it doesn't work at all.

I use only

```
ioHook.on('keydown', keydownHandler);
ioHook.on('keyup', keyupHandler);
```

to listen to global key events.

## Expected Behavior
Run builded Electron app and have working global key events there.

## Current Behavior
Build Electron app and global key events don't work there (but they work in dev mode). I gave all system permissions to app, but it still doesn't work.

## Steps to Reproduce (for bugs)
1. Build Electron app.
2. Run it.
3. Global key events doesn't works and weren't listened

## Context
I tried to give all permission to an app, but it didn't take any effect. Key event still doesn't work.

## Your Environment
* Version used: 0.3.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): Electron 3.0.0
* Operating System and version (desktop or mobile): macOS Mojave 10.14.3

**Comment by ekorolev** [comment] 2019-03-05 14:53
I have the same problem with my app.

**Comment by Djiit** [comment] 2019-03-06 13:59
Hello there, many users are fine with these handlers. Could you please share with us a minimal reproductible example ? Thanks !

**Comment by Djiit** [comment] 2020-01-20 09:37
Closing this one because of lack of information. Feel free to ping me here if you want to reopen it with more details.

**Closed by Djiit** 2020-01-20 09:37 UTC
Labels: bug, macos, waiting for feedback
