### ISSUE TITLE
Error: Cannot find module 'iohook'

### ISSUE THREAD

**Issue by egantz** [wilix-team/iohook#55] opened 2018-03-21 16:21 UTC
Hi, I have created an electron app that uses the ioHook library in it, as soon as I pack the app running (using `yarn run build`) and try to open the packaged app (both in mac and windows) the app crashes claiming it can't find the module.

If I run the app using `yarn start` or `electron .` it works perfectly!

## Expected Behavior
I would've expected it to get compiled with the rest of the libraries I use. 

## Current Behavior
Currently, the app crashes saying "Uncaught exception: Error: Cannot find module 'ioHook'" and then the stack trace.

## Possible Solution
Not sure, wish I had :)

## Steps to Reproduce (for bugs)
1. I added the library using `yarn add iohook`
2. imported the library using `const ioHook = require('iohook');`
3. Called it in my code and used the relevant event listeners.
4. Tried to wrap it as a packaged app and run it

## Context
I am trying to get the library running as part of an electron app without the need to install the library nowhere externally.

## Your Environment
* Version used: 1.7.0 (since this is the newest version I saw it is supported)
* Environment name and version (e.g. Chrome 39, node.js 5.4): NodeJS 9.2.0 (since this is the newest version I saw it is supported)
* Operating System and version (desktop or mobile): MacOS (High Sierra) and Windows 10 x64
* Link to your project: It's a private repo

Any ideas? Hope I gave enough info!

Thanks,
Eyal

**Comment by Djiit** [comment] 2018-03-21 17:05
Hi there,

Did you add the 'iohook' config in your package.json ? According to your env, i'll say : 
```
"iohook": {
  "targets": [
    "node-59",
    "electron-54"
  ],
  "platforms": [
    "win32",
    "darwin"
  ],
  "arches": [
    "x64",
    "ia32"
  ]
}
```
And then re-download your dependencies; this way it will fetch prebuild versions of iohook for node (the one you use in development and when using `electron .` AND for electron (the one you are supposed to use in production.

**Comment by egantz** [comment] 2018-03-21 17:09
Hi Djiit! Thanks so much for the quick reply. yeah I def did it and actually added all the electron versions available since I get an error when I don't do it. my ioHook config in my package.json looks like this:

```
"iohook": {
    "targets": [
      "node-59",
      "electron-47",
      "electron-54",
      "electron-57"
    ],
    "platforms": [
      "win32",
      "darwin"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }
```

Then, I am running `yarn add ioHook` to re-fetch the binaries.

But, still as soon as I try to compile the app and run the result - I get the same error that the ioHook library is missing.

**Comment by Djiit** [comment] 2018-03-21 18:34
That is weird. What is the error you get when you don't add "all the electron versions" ?

**Comment by egantz** [comment] 2018-03-22 01:02
that the electron version is missing and I need to install it, every time it shows about a different version

**Comment by Djiit** [comment] 2018-03-22 08:39
You should only have one electron target, the one corresponding to your current electron version. Can you copy/paste your results here ?

**Comment by mu-nil** [comment] 2018-03-24 03:25
First of all, where in packages.json do I put that? I am having the same issue here
``
App threw an error during load
Error: Cannot find module '/Users/user1/Dev/node/project1/node_modules/iohook/builds/electron-v57-darwin-x64/build/Release/iohook.node'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/Users/user1/Dev/node/project1/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
``

**Comment by egantz** [comment] 2018-04-02 14:57
Hi @Djiit thanks for the quick reply and sorry for my late response - I was busy with holiday times :)

So I did what you just told me to do (I am running NodeJS 9.2.0 so I am using build #59 and Electron 1.7.0 so I'm using build #57) I left only these two in the `package.json` file as you said.

I have packed the app using `electron-packager`, it packed the app successfully and as soon as I try to run the packed app I get this window: 
![image](https://user-images.githubusercontent.com/4982233/38201006-40e7c6ec-369f-11e8-8434-3335fa85a8bc.png)

Both in Windows and Mac.

Any ideas why does it happen??

**Comment by egantz** [comment] 2018-04-07 15:54
@Djiit help? 🙏🏻

**Comment by Djiit** [comment] 2018-04-07 22:32
Are you sure the prebuild version are presents in node_module/iohook ?
Also can you try to make a minimal app to reproduce the problem ? (i.e. electron and iohook only)

**Comment by egantz** [comment] 2018-04-26 22:43
Hi, @Djiit sorry for the late response.

1. Yeah, it seems like the prebuild versions are there, under `node_modules/iohook/builds`:
![image](https://user-images.githubusercontent.com/4982233/39086992-acb5d2ac-4567-11e8-9401-0e3d9c4c6aff.png)

and then each build has folders: `builds/Release/iohook.node`

2. Yeah, I just created a minimal side-project to see if it happens there and it doesn't! So I went back to my app, updated the library from 1.3 to 1.5, updated electron to 1.8.4 and nodeJS to 9.2.0, went to the package.json file and set the `electronVersion` to 1.8.4, the targets are `electron-57` and `node-59`, tried to run `yarn run build --overwrite`, then run the result on my mac and the same thing, tried with windows - same thing:
![image](https://user-images.githubusercontent.com/4982233/39335500-4acb90cc-4981-11e8-9659-0aa961d6118d.png)

I have a single file that requires electron and iohook, watching the `mouseclick` event to do a simple thing. can't see anything that could cause the problem.

any ideas?

**Comment by matthewshirley** [comment] 2018-04-27 20:49
`electron-rebuild` sometimes fixes these issues. https://github.com/electron/electron-rebuild

**Comment by egantz** [comment] 2018-04-27 21:01
@Djiit : I will push this project to a private repo and will invite you to it. many thanks, man! I am not building anything that is related to iohook, when I said "build" I referred to package the electron app with `electron-packager`

@matthewshirley When I try to use this library it throws an error looking for the library `electron-prebuilt` which I don't use. I am just using the `electron-packager` directly from the CLI. what do I do wrong here?

**Comment by matthewshirley** [comment] 2018-04-27 21:07
Is electron included as a dependency in your package.json?

**Comment by egantz** [comment] 2018-04-27 21:08
@matthewshirley only in `devDependencies`: `"electron": "^1.8.4",`

**Comment by matthewshirley** [comment] 2018-04-27 21:10
Do you have electron-rebuild installed globally or locally? If locally, run the command:

```./node_modules/.bin/electron-rebuild -f -w iohook```

**Comment by egantz** [comment] 2018-04-27 21:13
@matthewshirley doesn't help :(

**Comment by egantz** [comment] 2018-04-30 14:14
@Djiit Hi! sorry for the delay - added you yesterday as a contributor to the repo

**Comment by Djiit** [comment] 2018-05-02 15:57
Hey @egantz !

So I cloned our repository, I ran `yarn` and then `yarn start` : your app was working like a charm, printing the pressed mouse button in the terminal.

Note that I had to remove some condition regarding the log level of the app; but this is in no way related to ioHook.

I'm on a up-to-date 2013 MacBook Pro.

**Comment by egantz** [comment] 2018-05-02 17:28
Hi @Djiit ,

I actually referred to the `yarn run build` command which packs the app. I tried now to get rid of the `--asar` flag from the `electron-packager` command so the library won't make an archive file from the source code. that actually solved the problem! and my app works just fine. BUT! I do want to "hide" my code inside an archive file. so I assume once the app is in an archive, it can't find the `ioHook` library.

Any ideas? I am digging into it now and will come back with updates.

**Comment by Djiit** [comment] 2018-05-03 09:26
I tried to drop the --asar flag but it still doesn't work here. So strange :(

**Comment by egantz** [comment] 2018-05-04 16:45
really? ok so it works but I really want to use the asar in order to get to an archive file instead of the source files to be exposed. I will try to dig more into their documentation and will send some updates here

**Comment by egantz** [comment] 2018-05-05 16:26
Hi, now Windows' giving me hard times - `Error: %1 is not a valid Win32 application. \\?\C:\Windows\Help\log-analysis-win32-ia32\resources\app\node_modules\iohook\builds\electron-v57-win32-ia32\build\Release\iohook.node`

Any ideas? I see the file but it says it's invalid for some reason.

**Comment by Djiit** [comment] 2018-05-05 16:37
What did you change in your code or configuration ?

**Comment by egantz** [comment] 2018-05-05 17:05
nothing that was really related to the library itself. but I finally managed to pack the app, and tried to run it on windows x64 for the first time - and bumped into this error.

**Comment by egantz** [comment] 2018-10-30 23:38
Hi @Djiit, thanks for the follow up. We ditched this project for now, so I never got any updates about that. If we'll get back to it. I will drop here any updates we'll have. Thanks again!

**Comment by Djiit** [comment] 2018-10-31 07:08
Thanks for the feedback, I'm closing this now, feel free to comment here in the future and we'll reopen it.

**Comment by tbs-arpit** [comment] 2019-01-30 15:19
Facing this 
Screen grab is from dev tools of electron app 

![image](https://user-images.githubusercontent.com/41741151/51990304-c5afb380-24ce-11e9-9cb1-db9fee958380.png)

### Here is my package.json 

<details><summary>Package.json</summary>
<p>

```json
{
  "name": "<Project name :P>",
  "version": "1.19.0",
  "description": "A simple electron app for <project name :P>",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "electron main.js",
    "setup": "node build.js",
    "icon": "node icon.js"
  },
  "repository": {
    "type": "git",
    "url": "<Project URL>"
  },
  "iohook": {
    "targets": [
      "node-59",
      "electron-54"
    ],
    "platforms": [
      "win32",
      "darwin"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  },
  "cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "1.4.13"
  },
  "keywords": [
    "electron",
    "timeclockwizard",
    "windows",
    "mac"
  ],
  "author": "Arpit Vasani",
  "license": "ISC",
  "devDependencies": {
    "asar": "^0.14.0",
    "electron": "^1.7.10",
    "electron-installer-dmg": "^0.2.1",
    "electron-installer-windows": "*",
    "electron-packager": "^10.1.1",
    "electron-winstaller": "^2.6.3"
  },
  "dependencies": {
    "aws-sdk": "^2.340.0",
    "electron-rebuild": "^1.8.2",
    "electron-squirrel-startup": "^1.0.0",
    "iohook": "^0.3.1",
    "network": "^0.4.0",
    "util": "^0.11.1"
  }
}
```

</p>
</details>

**Comment by tbs-arpit** [comment] 2019-01-30 15:21
Facing this 
Screen grab is from dev tools of electron app 

![image](https://user-images.githubusercontent.com/41741151/51990304-c5afb380-24ce-11e9-9cb1-db9fee958380.png)

### Here is my package.json 

<details><summary>Package.json</summary>
<p>

```json
{
  "name": "<Project name :P>",
  "version": "1.19.0",
  "description": "A simple electron app for <project name :P>",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "electron main.js",
    "setup": "node build.js",
    "icon": "node icon.js"
  },
  "repository": {
    "type": "git",
    "url": "<Project URL>"
  },
  "iohook": {
    "targets": [
      "node-59",
      "electron-54"
    ],
    "platforms": [
      "win32",
      "darwin"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  },
  "cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "1.4.13"
  },
  "keywords": [
    "electron",
    "windows",
    "mac"
  ],
  "author": "Arpit Vasani",
  "license": "ISC",
  "devDependencies": {
    "asar": "^0.14.0",
    "electron": "^1.7.10",
    "electron-installer-dmg": "^0.2.1",
    "electron-installer-windows": "*",
    "electron-packager": "^10.1.1",
    "electron-winstaller": "^2.6.3"
  },
  "dependencies": {
    "aws-sdk": "^2.340.0",
    "electron-rebuild": "^1.8.2",
    "electron-squirrel-startup": "^1.0.0",
    "iohook": "^0.3.1",
    "network": "^0.4.0",
    "util": "^0.11.1"
  }
}
```

</p>
</details>

**Comment by yogeshjog** [comment] 2019-04-15 22:16
Try this.
https://www.youtube.com/watch?v=6o9xybTYlLU

For audio : https://app.box.com/s/6gusokl3srmj85iyohavoyjvwmesfapg

**Comment by vasani-arpit** [comment] 2019-04-17 05:54
Nice video. Thanks for taking efforts for it.

**Comment by yogeshjog** [comment] 2019-04-18 19:13
> Nice video. Thanks for taking efforts for it.

Welcome! 

Lots of Thanks to iohook team for making such an awesome module.

**Comment by chad187** [comment] 2019-07-24 04:41
> Thanks for the feedback, I'm closing this now, feel free to comment here in the future and we'll reopen it.

I didn't see any resolution

**Comment by chad187** [comment] 2019-07-24 04:44
> Hi @Djiit ,
> 
> I actually referred to the `yarn run build` command which packs the app. I tried now to get rid of the [`--asar` flag](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#asar) from the `electron-packager` command so the library won't make an archive file from the source code. that actually solved the problem! and my app works just fine. BUT! I do want to "hide" my code inside an archive file. so I assume once the app is in an archive, it can't find the `ioHook` library.
> 
> Any ideas? I am digging into it now and will come back with updates.

this is exactly the problem I am still stuck on. Please reopen the issue.

**Comment by chad187** [comment] 2019-07-27 15:48
> Hi @Djiit ,
> 
> I actually referred to the `yarn run build` command which packs the app. I tried now to get rid of the [`--asar` flag](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#asar) from the `electron-packager` command so the library won't make an archive file from the source code. that actually solved the problem! and my app works just fine. BUT! I do want to "hide" my code inside an archive file. so I assume once the app is in an archive, it can't find the `ioHook` library.
> 
> Any ideas? I am digging into it now and will come back with updates.

I also found it to work without asar and fail with asar. So I ran asar with iohook unpackaged and I got this error
![Capture](https://user-images.githubusercontent.com/8450028/61996644-4b11bc00-b04b-11e9-8704-3c30065bb919.PNG)

**Comment by zxc23** [comment] 2019-08-06 17:46
Experiencing the above on some PCs and not others. Quite weird. They are all Win32 x64 PCs.

![error](https://user-images.githubusercontent.com/5210652/62563172-ca15b880-b8c5-11e9-9c7b-865198b5e6f5.jpg)

**Comment by taoabc** [comment] 2019-08-20 11:47
Same issue here, works well with folder. BUT, when I pack folder to asar, and run from asar, it gives me message: xxx.tmp.node could not be found. when I extract the same app.asar to app folder, it works.

**Comment by taoabc** [comment] 2019-08-20 12:14
I think the issues is caused by dependency of uiohook.dll, electron could recognize .node file, and extract it to temp folder, then change require path to temp .node path internally, but It can't extract dll files.
I suggest compile uiohook to iohook.node with static link, not dynamic link.
Or do not pack it to asar, just folder.

**Comment by zxc23** [comment] 2019-08-20 12:19
After installing my application, I've noticed that `resources/` has `app.asar.unpacked` which contains `node_modules/iohook/`. It looks like on installation, iohook is unpacked from the asar (I guess it needs to be in order to be used properly?). But on some computers, it can't locate the iohook.node file, which in my case would be located in `resources\app.asar.unpacked\node_modules\iohook\builds\electron-v70-win32-x64\build\Release`

**Comment by woniesong92** [comment] 2019-12-13 05:18
I face the same issue on a fresh electron quickstart app.

#### Reproduction steps:

```
$ git clone https://github.com/electron/electron-quick-start
# Go into the repository
$ cd electron-quick-start
# Install dependencies
$ yarn
# Run the app
$ yarn start
# Add iohook
$ yarn add iohook
# Require it in main.js
```

#### main.js
```
const ioHook = require("iohook");
ioHook.on("keyup", event => {
  console.log(event); // {keychar: 'f', keycode: 19, rawcode: 15, type: 'keup'}
});
ioHook.start();
```

#### error

```
App threw an error during load
Error: Cannot find module '/Users/d/tmp/electron-quick-start/node_modules/iohook/builds/electron-v75-darwin-x64/build/Release/iohook.node'
Require stack:
- /Users/d/tmp/electron-quick-start/node_modules/iohook/index.js
- /Users/d/tmp/electron-quick-start/main.js
- /Users/d/tmp/electron-quick-start/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7613:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/d/tmp/electron-quick-start/node_modules/iohook/index.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
```

**Comment by nolior** [comment] 2020-01-02 07:02
I'm running into the same issue ^

**Comment by inomdzhon** [comment] 2020-03-10 21:28
Hm, it's simple for solve.

For example, if you have error like this
```
Error: Cannot find module '../node_modules/iohook/builds/electron-v75-darwin-x64/build/Release/iohook.node'
```

See part of error message `electron-v75-darwin-x64`, put their to `package.json`
```
  "iohook": {
    "targets": [
      "electron-75"
    ],
    "platforms": [
      "darwin"
    ],
    "arches": [
      "x64"
    ]
  }
```
and install `iohook` again
```
npm i -S iohook
```

**Comment by apodolny** [comment] 2020-04-04 23:22
A note to anyone installing with Yarn: be sure to remove iohook from your global cache before reinstalling or you won't end up with the builds for the environments that you've added.

`yarn cache clean iohook`

**Comment by m1n0s** [comment] 2020-06-12 13:28
I've faced this issue as well on my end and no matter what I'm trying from the advices from this issue - neither `yarn` nor `npm` can download proper node binding.

package.json
```
"iohook": {
      "targets": [
        "electron-76"
      ],
      "platforms": [
        "win32",
        "darwin",
        "linux"
      ],
      "arches": [
        "x64",
        "ia32"
      ]
    },
```
But inside node_modules I can see only 1 binding probably based on my mac host env.
![image](https://user-images.githubusercontent.com/12004923/84506218-b1d1af80-acc7-11ea-94b0-070da88e0f2c.png)

I've tried to clean caches, reinstall all modules with both `yarn` and `npm` and nothing helped and I still have `Error: Cannot find module '/Users/leontii.hrabovetskyi/Projects/desktop-communicator/node_modules/iohook/builds/electron-v76-darwin-x64/build/Release/iohook.node'`

Any further advices please? I can download `electron-v76-darwin-x64` manually and place it inside a folder from screenshot above but this doesn't work for CI obviously.

**Comment by felipe-augusto** [comment] 2020-07-30 13:46
I'm having the same problem:

```sh
Cannot find module '/Users/myuser/apps/myproject/node_modules/electron/dist/
Electron.app/Contents/Resources/electron.asar/renderer/
builds/electron-v80-darwin-x64/build/Release/iohook.node'
```

And the file exists inside the `node_modules/iohook` folder:

![image](https://user-images.githubusercontent.com/9551950/88929702-dcb09c80-d250-11ea-819f-53e2374e10c7.png)


Any ideas?

**Comment by zxc23** [comment] 2020-07-30 14:02
Looks like I forgot to reference and post in this issue.

An update: I've had multiple confirmations that this problem was resolved by installing Microsoft Visual C++ Redistributable on the machines via https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads.

These issues are all related:

#55 
#167
#193
#195
#224 
#245

**Comment by felipe-augusto** [comment] 2020-07-30 14:06
@zxc23 actually I'm not on windows, I don't think that solves my problem :(

**Comment by zxc23** [comment] 2020-07-30 14:09
@felipe-augusto Oh, that's too bad, I have no ideas. I had the problem on Windows 10 machines and this was the only solution which worked for them.

**Comment by felipe-augusto** [comment] 2020-07-30 14:15
@zxc23 thank you for your reply, I was able to find the solution, I was using the latest electron version, but it seems, for now, it is only supported on 8.x.x, this comment here explains basically everything you need to do:

https://github.com/wilix-team/iohook/issues/241#issuecomment-652517691

**Comment by danikoala** [comment] 2020-08-04 07:12
Can we have a solution for Electron 9.x.x??

**Comment by gelpiu-developers** [comment] 2020-12-02 07:31
Same behaviour in Electron 11

**Comment by lmr520** [comment] 2021-05-25 06:32
> @zxc23 thank you for your reply, I was able to find the solution, I was using the latest electron version, but it seems, for now, it is only supported on 8.x.x, this comment here explains basically everything you need to do:
> 
> [#241 (comment)](https://github.com/wilix-team/iohook/issues/241#issuecomment-652517691)

I change to 8.5.5 ,I added files to builds like ,what do more for it with you ?
<img width="650" alt="截屏2021-05-25 下午2 30 08" src="https://user-images.githubusercontent.com/39985568/119449859-bae74f80-bd65-11eb-996e-94aecb1c1cb7.png">

**Comment by ash0x0** [comment] 2021-06-11 19:13
Closing as irrelevant. This doesn't seem to be an issue anymore. Feel free to reopen with some more up-to-date info.

**Closed by ash0x0** 2021-06-11 19:13 UTC
Labels: electron, waiting for feedback

**Comment by dement6d** [comment] 2022-05-07 13:55
> Closing as irrelevant. This doesn't seem to be an issue anymore. Feel free to reopen with some more up-to-date info.

still an issue on Windows 10 x64
installing visual c++ didnt help

> node -v
`v16.15.0`

> npm -v
`8.5.5`

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Demented\Desktop\keeloger\node_modules\iohook\builds\node-v93-win32-x64\build\Release\iohook.node'      
Require stack:
- C:\Users\Demented\Desktop\keeloger\node_modules\iohook\index.js
- C:\Users\Demented\Desktop\keeloger\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Demented\Desktop\keeloger\node_modules\iohook\index.js:24:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Demented\\Desktop\\keeloger\\node_modules\\iohook\\index.js',
    'C:\\Users\\Demented\\Desktop\\keeloger\\index.js'
  ]
}
```


```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "iohook": {
    "targets": [
      "electron-75"
    ],
    "platforms": [
      "darwin"
    ],
    "arches": [
      "x64"
    ]
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "iohook": "^0.9.3"
  }
}
```

**Comment by dement6d** [comment] 2022-05-09 03:52
I built iohook myself and put my `node-v93-win32-x64` folder into `node_modules/iohook/builds` and got the same `iohook.node is not a valid Win32 application.` error upon running `node .\index.js`:
```
node:internal/modules/cjs/loader:1189
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\C:\Users\Cuff\Desktop\keeloger\node_modules\iohook\builds\node-v93-win32-x64\build\Release\iohook.node is not a valid Win32 application.
\\?\C:\Users\Cuff\Desktop\keeloger\node_modules\iohook\builds\node-v93-win32-x64\build\Release\iohook.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Cuff\Desktop\keeloger\node_modules\iohook\index.js:24:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by vimalAtLR** [comment] 2023-03-30 12:47
same error I'm getting in linux 
please give me some solution
